#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'sudo'

cookbook 'chef-solo-search',
  :git => 'https://github.com/edelight/chef-solo-search.git'
cookbook 'user',
  :git => 'https://github.com/fnichol/chef-user.git'
cookbook 'transmission',
  :git => 'https://github.com/chef-developers/transmission.git'

cookbook 'python',
  :git => 'https://github.com/opscode-cookbooks/python'
cookbook 'bag_config', # attributes taken from databags
  :git => 'https://github.com/heavywater/chef-bag_config'
cookbook 'flexget',
  :git => 'https://github.com/chef-developers/chef-flexget.git'

cookbook 'htpc',
	:git => 'https://github.com/chef-developers/cookbook-htpc.git'			

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
